import SideBar from "@/components/SideBar";
// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "ScrolloGram",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen flex-col md:flex-row relative md:overflow-hidden">
      <div className="md:p-3 md:w-20 xl:w-72 border-t md:border-r order-last md:order-none h-12 md:h-full ">
        <SideBar />
      </div>
      <div className="w-full h-full p-4 flex-grow">{children}</div>
    </div>
  );
}
